### ISSUE TITLE
[Minor]: updating the list of planners

### ISSUE THREAD

**Issue by guicho271828** [nergmada/pddl-reference#34]
Link to page(s) with issue: 
- https://nergmada.github.io/pddl-reference/guide/whatisplanner.html#list-of-planners
-
-
Quote of current error:

Proposed correction:
You could post a link to the planning competition websites, and also to the IPC booklet pdf (or you can host it by getting a permission --- you will mostly likely get one).

**Comment by nergmada** [comment]
Hi thanks for this - do you have a link to the IPC booklet you mention, I haven't found that in the course of my research but I haven't done extensive work on Additional resources

- Adam

**Comment by guicho271828** [comment]
I think I can just share it with you -- you can search yourself from the title then

**Comment by guicho271828** [comment]
I sent you the pdfs via email

**Comment by nergmada** [comment]
I have received your emails, I'll reach out to the authors to seek permission, but I think I have at least one of each in the department with me so it shouldn't take too long. Thank you for your help!

**Comment by guicho271828** [comment]
note that you better find the original, there might be annotations here and there that I added.

**Comment by nergmada** [comment]
Hi, I am closing this issue as we have introduced an A to Z list of AI planners, this list is by no means complete but it establishes the fact that our wiki knowledge base for planners is still lacking major information and provides a starting point for our users who are unsure about the existence of other planners to find them.

Thank you for providing this feedback, it's given me a chance to really consider the best way to deal with incomplete information and is exactly the kind of feedback I want to encourage

If you have any other further issues with the guide please do not hesitate to file an issue here and I will aim to address it
